# Generated by Django 3.0.3 on 2020-07-10 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bit',
            new_name='starting_bid',
        ),
    ]
