# Generated by Django 3.0.3 on 2020-07-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200713_0014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
