# Generated by Django 3.0.3 on 2020-07-12 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_delete_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('starting_bid', models.IntegerField()),
                ('image_path', models.CharField(max_length=80)),
                ('category', models.CharField(default='None', max_length=20)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
