# Generated by Django 3.0.3 on 2020-07-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Gad', 'Gadget'), ('Fas', 'Fashion'), ('Dev', 'Development'), ('Acc', 'Accessory')], max_length=5),
        ),
    ]
