# Generated by Django 3.0.3 on 2020-07-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='auction_id',
            new_name='auction',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='user',
        ),
    ]
