# Generated by Django 3.0.3 on 2020-07-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200713_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
